spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text

  datasource:
    url: jdbc:postgresql://localhost:5432/testpilot
    username: postgres
    password: Nilorac
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
